.github/workflows/github-actions-demo.yml, .github/workflows/github-actions.yml
This PR adds smoke tests for the main pipelines using github actions. It only runs the pipelines in "`dry-run`" mode but this should catch problems where the pipelines are not configured correctly. 
These are the snakemake files tested right now
```
pipelines/training_association_testing.snakefile
pipelines/seed_gene_discovery.snakefile
pipelines/association_testing_pretrained.snakefile
```
=> Add pipeline smoke tests using github actions 

.github/workflows/github-actions.yml, TODOS.md, deeprvat/seed_gene_discovery/README.md, deeprvat/seed_gene_discovery/config.yaml, deeprvat/seed_gene_discovery/evaluate.py, deeprvat/seed_gene_discovery/seed_gene_discovery.py, deeprvat_env.yaml, deeprvat_env_no_gpu.yml
This PR updates the example data and `seed gene discovery pipeline` so that they work together.
- `is_plof` was added to` annontations.parquet` using this code:
```python
anno = pd.read_parquet("annotations.parquet")
if 'is_plof' not in anno.columns:
is_plof = pd.Series([False] * len(anno), index=anno.index)
for c in ('splice_acceptor_variant', 'splice_donor_variant',
'frameshift_variant', 'stop_gained', 'stop_lost', 'start_lost'):
is_plof |= (anno[f'Consequence_{c}'] > 0)
anno["is_plof"] = is_plof
anno.to_parquet("annotations.parquet")
```
- All references to `genes.parquet` were changed to the correct name `protein_coding_genes.parquet`
- References to `combined_UKB_NFE_AF` was changed to `MAF`
- `plotnine` was added as a dependency to the deeprvat environment.
- README was updated to …
=> Fix seed gene discovery pipeline with example data

README.md
Updates the readme to clarify that to use cuda you need to install the environment using mamba.
This issue shows the problem: https://github.com/PMBio/deeprvat/issues/16
=> Add note on deeprvat environment

deeprvat/preprocessing/preprocess.py
Removes the sorting of samples in `process_sparse_gt` this step was used for shuffling samples but assumed that the sample names were only numeric.
=> Remove sample sorting from preprocessing

deeprvat/annotations/annotations.py
This PR solves an issue in the `process_chunk_addids` in the annotation pipeline.
Currently if there are any duplicates in the chunk the assert will fail since we save the chunk shape before dropping the duplicates.
The assert is meant to check the merging of the chunk and the variants and not check for duplicates in the chunk.
=> Save chunk shape after dropping duplicates

README.md, docs/annotations.md, docs/seed_gene_discovery.md
Update links in main readme to point to https://deeprvat.readthedocs.io.
Also fixes a few internal links in the docs that pointed to github.
=> Point docs to RTD

deeprvat/deeprvat/associate.py, deeprvat/deeprvat/config.py, deeprvat/metrics.py, deeprvat/utils.py
Adding docstrings for functions in multiple files.
=> Update docstrings for functions

.github/workflows/github-actions.yml
This PR updates the snakemake smoketests so they use the same conda env as the other tests, this is a bit slower but more stable since the [snakemake github action](https://github.com/snakemake/snakemake-github-action) always uses the latest version of snakemake.
And this broke our tests after the latest release (https://github.com/snakemake/snakemake/releases/tag/v8.0.1) of snakemake.
=> Fix failing snakemake smoke tests 

.github/workflows/autoblack_pull_request.yml, .github/workflows/docs-tests.yml, .github/workflows/github-actions.yml, .github/workflows/test-runner.yml, deeprvat/deeprvat/evaluate.py, deeprvat/seed_gene_discovery/seed_gene_discovery.py
Node.js 16 actions are deprecated so we update the github action dependecies to newer version with node v20.
All actions on this branch should pass/run.
=> Update github actions to node v20

deeprvat/annotations/annotations.py, pipelines/resources/absplice_download.snakefile, pipelines/resources/environment_spliceai_rocksdb.yaml
This PR is addressing the three open issues #61, #62 and #63 posted by user @Jonas-B-Frank, namely
- a mistake in the output of `rule download_rocksdb` in `absplice_download.snakefile`
-  a nonfunctional version tag in `environment_spliceai_rocksdb.yaml`
- missing consequences considered in the VEP output
To test the pipeline, it has to be run locally and the output has to be checked. 
As described in the documentation for the annotation pipeline
=> fixed bugs in the annotation pipeline based on issues #61, #62 and #63.

deeprvat/cv_utils.py, deeprvat/data/dense_gt.py, deeprvat/deeprvat/associate.py, deeprvat/deeprvat/train.py, deeprvat/utils.py, example/config.yaml, pipelines/association_testing/association_dataset.snakefile, pipelines/association_testing_pretrained.snakefile, pipelines/cv_training/cv_burdens.snakefile, pipelines/cv_training/cv_training.snakefile, pipelines/cv_training/cv_training_association_testing.snakefile, pipelines/training/config.snakefile, pipelines/training/train.snakefile, pipelines/training/training_dataset.snakefile, pipelines/training_association_testing.snakefile, tests/deeprvat/test_train.py
Reverts PMBio/deeprvat#71 due to bug introduced with this commit.
=> Revert "Feature streamline cv training"

deeprvat/data/dense_gt.py
Casts sample names to string to allow for samples names to contain non-digits. 
Pytests passed.
=> Cast sample names to string

.github/workflows/autoblack_pull_request.yml, .github/workflows/docs-tests.yml, .github/workflows/github-actions.yml, .github/workflows/test-runner.yml, .readthedocs.yaml
Reverts the changed runner base images from 24.04 to ubuntu-latest.
24.04 was not deployed yet so no actions started.
The actions should run now.
=> Change GitHub action runner to ubuntu-latest

.gitignore, docs/conf.py, docs/requirements.txt
This PR updates the doc build process so that we add the authors to the doc automatically from the `citations.cff` file, so we don't have to update them i 3 separate places.
To test this pr you can first build the docs and look at the author list in the docs:
`make html && open _build/html/index.html`
Then try adding a new author to the citations.cff example:
```yaml
...
- given-names: Oliver
family-names: Stegle
orcid: 'https://orcid.org/0000-0002-8818-7193'
- given-names: John
family-names: Doe
orcid: 'https://orcid.org/0000-0002-8818-7193'
```
Build the docs again
`make html && open _build/html/index.html`
The docs should now contain the new author:
**_Note_**:
This will add new authors to the docs that were not present in the docs (but exist in the citations.cff).
Before:
`© Copyright …
=> Create author list dynamically in docs

.github/workflows/pipeline-tests.yml, .github/workflows/run-pipeline.yml
This PR adds support for a `postrun_cmd` to the `run-pipeline` workflow. This enables you to add an extra command to run after the pipeline is done. For example, you could add a script to verify the output.
To test this you can check out this pr and add a `postrun_cmd` to the yaml for example:
```yaml
jobs:
Smoke-RunTraining:
uses: ./.github/workflows/run-pipeline.yml
with:
pipeline_file: ./pipelines/run_training.snakefile
environment_file: ./deeprvat_env_no_gpu.yml
postrun_cmd: echo "Hello World from post"
Pipeline-Tests-RunTraining:
needs: Smoke-RunTraining
uses: ./.github/workflows/run-pipeline.yml
with:
pipeline_file: ./pipelines/run_training.snakefile
environment_file: ./deeprvat_env_no_gpu.yml
dry_run: false
postrun_cmd: python --version
```
You can also add a post_cmd that should …
=> Post run cmd in pipeline tests

.github/workflows/pipeline-tests.yml, .github/workflows/run-pipeline.yml
Updates the test-pipeline to add support for extra snakemake flags.
You can now pass extra flags to the snakemake cmd using the `pipeline_extra_flags` parameter.
```yml
jobs:
Smoke-RunTraining:
uses: ./.github/workflows/run-pipeline.yml
with:
pipeline_file: ./pipelines/run_training.snakefile
environment_file: ./deeprvat_env_no_gpu.yml
pipeline_extra_flags: --verbose # Example of adding the verbose flag
```
=> Add support pipeline test extra flags

pipelines/config/deeprvat_annotation_config.yaml
This PR changes the default values in the annotation config file to use the normalized bcf files from the preprocessing pipeline as an input. 
a smoke test with the example data will be performed automatically by github, which should make sure that the paths all exist in the example data, the pipeline was tested locally with bcf files.
=> changed config to use normalized bcfs as default input.

pipelines/annotations.snakefile
When VCF files are normalized, sometimes there are multiple IDs for each variant concatenated with a semicolon(;) THis however leads to problems with the `#Uploaded_variation` column in VEP. This PR regenerates the IDs and makes sure each variant gets a unique ID. 
Related to Issue #76, specifically this comment https://github.com/PMBio/deeprvat/issues/76#issuecomment-2139008285
Tested locally on example data
Run pipeline locally
=> Regenerate IDs for VEP annotation inout VCFs

deeprvat/deeprvat/models.py, deeprvat/deeprvat/train.py
updated linear model for multi-phenotype training and added burden reverse functionality
=> Update linear model

.github/workflows/pipeline-tests.yml, deeprvat/deeprvat/config.py, docs/input_data.md, docs/quickstart.md, example/config/deeprvat_input_training_config.yaml, pipelines/run_training.snakefile
Includes example config setup for running the training-only pipeline. This also updates the docs to reflect these updates as well as, adds additional PyTests to the GitHub actions for testing the `example/config` files.
```
DEEPRVAT_REPO_PATH="[path_to_deeprvat]"
mkdir deeprvat_train
cd deeprvat_train
ln -s "$DEEPRVAT_REPO_PATH"/example/* .
ln -s config/deeprvat_input_training_config.yaml . #get the corresponding config.
snakemake -j 1 --snakefile "$DEEPRVAT_REPO_PATH"/pipelines/run_training.snakefile
```
=> Create PyTests for config file setups

.github/workflows/pipeline-tests.yml, .github/workflows/run-pipeline.yml, deeprvat/deeprvat/train.py, tests/deeprvat/compare_reference.py, tests/deeprvat/training_association_testing/deeprvat_config.yaml
Adds additional GitHub actions for comparing pipeline output results in relation to the current working/PR branch to main branch. This verifies the results on the example data stay the same, within a specified tolerance, during code changes.
When the `deterministic` flag is set, a seed is set to address differences between runs. This is imperfect, hence the tolerance specification in [/tests/deeprvat/compare_reference.py](https://github.com/PMBio/deeprvat/blob/feature/chunked-writer-precomputed-burdens-testing-combo/tests/deeprvat/compare_reference.py)
Running the various pipelines on two different testing branches, with the deterministic flag set in the config file, and comparing the outputs in the relevant GitHub action call that uses a test in compare_reference.py
=> Add additional Github Action for checking pipeline output values

pipelines/preprocessing/qc.snakefile
Fixing issue  #134 
This update addresses an issue with the bcftools allelic imbalance filtering command introduced in versions later than v1.16. Specifically, we want to **exclude (write) variants only where all heterozygous calls have an allele balance (AB) < 0.15, but keep the variant if any heterozygous call has an AB > 0.15**.
The previous bcftools allelic imbalance filtering command 
```
bcftools query --format '%CHROM\t%POS\t%REF\t%ALT\n' --exclude 'COUNT(GT="het")=0 || 
(GT="het" & ((TYPE="snp" & (FORMAT/AD[*:1] / FORMAT/AD[*:0]) > 0.15) | (TYPE="indel" & (FORMAT/AD[*:1] / FORMAT/AD[*:0]) > 0.20)))' {{input}}
``` 
only had the intended behavior until bcftools v1.16. With newer versions, bcftools filtering logic seem sot have changed from an _any_  to _all_ evaluation. 
This …
=> Fix Allelic Imbalance Filtering Logic for bcftools v1.16+

deeprvat/deeprvat/associate.py
This update skips association testing for constant burden vectors when using SEAK, as SEAK returns p-values of 0 for such cases. This can cause genes to be falsely considered significant. 
Verified that association testing with all constant burdens now returns nan p-values. Verified that burden testing of non-constant burden behaves as before.
=> skip seak association testing if all burdens are constant

deeprvat/deeprvat/associate.py
Removes the metadata description field from the BgenWriter, due to a bug in the BgenWriter/BgenReader code that causes bugs in the probabilities/dosages calculations from the resulting .bgen file.
Tested by creating example datasets and using BgenWriter and BgenReader to create and view the resulting incorrect/errored .bgen, respectively. 
Note: In future version releases of the bgen repository, this function may again be working correctly and the metadata field could be added back in. 
Current problematic bgen version : 1.7.2
=> Remove BgenWriter metadata field.
